nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    MYA_FEATURE_FLAG: 'true'
    NODE_ENV: "aat"
    EVIDENCE_UPLOAD_QUESTION_PAGE_ENABLED: 'false'
    EVIDENCE_UPLOAD_QUESTION_PAGE_OVERRIDE_ALLOWED: 'true'
